### ISSUE TITLE
Истёкшая инвайт-ссылка в Telegram

### ISSUE THREAD

**Issue by ioan-navari** [TulpaWiki/website#1]
ссылка на тг канал истекла

**Comment by toby3d** [comment]
Ссылка-инвайт в подвале сайта рабочий, его никто не деактивировал. Аналогично и со ссылкой в README.md. О какой именно ссылке речь?

**Comment by toby3d** [comment]
Скорее всего платформа Telegram действительно как-то поменяла работу инвайтов и никто этого не заметил. А старые ссылки работали для тех, кто ими пользовался. Я заглянул в настройки чата и увидел коллизию, обновил инвайты. Надеюсь, это решает проблему.
